sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master # trigger release only for PRs and changes pushed to master branch
notifications:
  email: false
node_js:
  - '12'
before_install:
  - npm i -g npm@^6.10.0
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
  - npm run semantic-release